# This script scrapes the most recent 90-day-median prices for a list of items from https://warframe.market using the warframe.market API.
# The script was created by 1Xanaton4You on 20.07.2026
# This is an open source script under GNU GENERAL PUBLIC LICENSE Version 3.
#
# Files needed to run the WarframeMarketScraperV2.py script:
#   ItemsFinder.py (in the same directory as this script)
#   warframe_market_database.py (is generated by ItemsFinder.py)
#
# I wrote this scrip to get a easier overview over the current prices on the warframe.market.
#
# How to use this script on first use:
# 1. On windows open a command prompt by typing cmd into the windows seach field.
# 2. Type "phyton" and press enter to check if you have phyton installed on your system.
#    2a. If you do not get something like this {Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] on win32
#                                               Type "help", "copyright", "credits" or "license" for more information.}
#        you first have to install Phyton on your system (https://www.python.org/downloads/).
#    2b. Make sure that the "requests" packet is installed in your Python enviroment. To check this type in "python -m pip list".
#        If the list shows something like this {requests           2.34.2} it is installed. If it is not installed type in 
#        "python -m pip install requests" to install it.
#    2c. If you have a Phyton version and the requests packet installed type exit() and press enter to leave the phyton prompt.
# 3. Alter the [Set this according to your needs] part of the sript according to your needs, in case you have added new lists in ItemFinder.py.
# If you have already done steps 1 to 3 at least once start at step 4:
# 4. Start the script by double clicking the WarframeMarketScraperV2.py
# 5. Select if you want to scan the warframe market for selleable items and store the results into "warframe_market_database.py" (y=yes, n=no).
# 6. Select if you want to scrape all defined item lists (y) or select a specific list (n). Choose the list number, if you want to scrape a single list.
# 7. Wait for the results. You can save the scraped results in a CSV-file when the scraping is done, if you choose to do so.
#    The CSV-files will be created in the folder this script runs from.
import importlib
import urllib.parse as parse
import urllib.request
from urllib.request import urlopen as req_url
import json
import string
#import webbrowser
import csv
import sys
from pathlib import Path
from datetime import datetime
import tracemalloc
from time import sleep
import ItemFinder
try:
	import warframe_market_database
except ModuleNotFoundError:
	warframe_market_database = None

def warframeMarketScraper(mode):
	# --------------------------------------- [START: Set this according to your needs] ---------------------------------------------
	# Switches for debugging (only for debug)
	enableDebugDump = 0 # Set this 1, if you want to dump all the received data or 2 if you only want the final find data into a txt-file.
	enableDebugTestList = 0 # Set this 1, if you want to use a test list for debugging at selection 9.
	STATISTICS_API = 'https://api.warframe.market/v1/items/'
	# Define the name of the itemLists
	# The item lists are generated by the CATEGORY_RULES defined in ItemFinder.py
	# If you add new lists you need to alter the code below to add them to the selecteable lists.
	if mode == "manually":
		if enableDebugDump > 0:
			print("enableDebugDump=" + str(enableDebugDump))
		if enableDebugTestList == 1:
			print("What are you interested in [1-WarframeSets, 2-SentinelAndAwSets, 3-PrimeWeaponSets, 4-SyndicateWeapons, 5-OtherNonPrimeWeapons, 6-Arcanes, 7-Mods, 8-RivenMods, 9-Relics, 10-TestList(DEBUG)]?")
		else:
			print("What are you interested in [1-WarframeSets, 2-SentinelAndAwSets, 3-PrimeWeaponSets, 4-SyndicateWeapons, 5-OtherNonPrimeWeapons, 6-Arcanes, 7-Mods, 8-RivenMods, 9-Relics]?")
		answer = input()
	else:
		answer = mode
	#breakpoint()
	if answer == "1":
		# This is a list of all currently available probe warframe sets
		listName = "WarframeSets"
		my_itemList = warframe_market_database.categories["warframes"]
	elif answer == "2":
		listName = "SentinelAndAW"
		my_itemList = warframe_market_database.categories["companions"]
	elif answer == "3":
		listName = "PrimeWeaponSets"
		my_itemList = warframe_market_database.categories["prime_weapons"]
	elif answer == "4":
		listName = "SyndicateWeapons"
		my_itemList = warframe_market_database.categories["syndicate_weapons"]
	elif answer == "5":
		listName = "NonPrimeWeapons"
		my_itemList = warframe_market_database.categories["weapons"]
	elif answer == "6":
		listName = "Arcanes"
		my_itemList = warframe_market_database.categories["arcanes"]
	elif answer == "7":
		listName = "Mods"
		my_itemList = warframe_market_database.categories["mods"]
	elif answer == "8":
		listName = "RivenMods"
		my_itemList = warframe_market_database.categories["riven_mods"]
	elif answer == "9":
		listName = "Relics"
		my_itemList = warframe_market_database.categories["relics"]
	elif answer == "10" and enableDebugTestList == 1:
		listName = "Test"
		my_itemList = warframe_market_database.categories["test"]
		#my_itemList = ['volnus_prime_set', 'corvas_prime_set']
	else:
		print("Error: Nothing to scrape. Only viable options are 1 to 9!")
		answer = input()
		sys.exit()
	# --------------------------------------- [END: Set this according to your needs] ---------------------------------------------
	# Initialisation of variables
	my_data = [['Date','Volume','Minimum', 'Maximum', 'Median', 'Item']]
	#newLine = []
	maxMedianLineIndex = 1
	currentLineIndex = 1
	maxMedian = 0
	parseDataStr = ""
	if enableDebugDump > 0:
		debugJonsonDump = ""
	fileNameAddon = ""
	#breakpoint()
	# The scipt starts here
	if answer == "9":
		fileNameAddon = "DEBUG_"
	if enableDebugDump == 1:
		parseDataStr = "fileNameAddon=" + fileNameAddon + "\n"
		print(parseDataStr)
		debugJonsonDump = debugJonsonDump + parseDataStr
		parseDataStr = "Used item list " + answer + " =" + str(my_itemList) + "\n\n"
		print(parseDataStr)
		debugJonsonDump = debugJonsonDump + parseDataStr
	# Loop through the item list and extract the desired data
	for item in my_itemList:
		# scrape the current item prices from warframe.market
		itemStr = string.capwords(item.replace('_', ' '))
		try:
			main_url = req_url(STATISTICS_API + item + '/statistics') 
		except:
			main_url = None
			parseDataStr = "Error: The item [" + item + "] does not exist on warframe.market!"
			print(parseDataStr)
			if enableDebugDump > 1:
				debugJonsonDump = debugJonsonDump + (parseDataStr + "\n")
			# Load default values
			parsed_min = 0
			parsed_max = 0
			parsed_median = 0
			parsed_volume = 0
			date_time = "9999-99-99"
		else:
			#breakpoint()
			
			data = main_url.read()
			main_url = None
			parsed = json.loads(data)
			data = None
			# Uncomment the next 4 lines to check what data the website returns
			if enableDebugDump == 1:
				if currentLineIndex == 1:
					parseDataStr = "Received data for item " + itemStr + " [" + json.dumps(parsed) + "]\n"
				else:
					parseDataStr = "\nReceived data for item " + itemStr + " [" + json.dumps(parsed) + "]\n"
				print(parseDataStr)
				debugJonsonDump = debugJonsonDump + parseDataStr
			#breakpoint()
			dataSetIndex = -1 # by default use the last set which is the last recorded day
			try:
				nbrOfSets = int(len(parsed['payload']['statistics_closed']['90days']))
			except:
				parseDataStr = "Error: Number of sets could not be extracted. Skipping [mod_rank=0 search."
				print(parseDataStr)
				if enableDebugDump == 1:
					debugJonsonDump = debugJonsonDump + (parseDataStr + "\n")
			else: 
				if listName == "Arcanes" or listName == "Mods":
					# Only for Arcane and Mods parse the mod_rank of the last set
					if enableDebugDump == 1:
						parseDataStr = "Start search for [mod_rank=0].\nNbr. of sets to search= " + str(nbrOfSets) + "\n"
						print(parseDataStr)
						debugJonsonDump = debugJonsonDump + parseDataStr
					#breakpoint()
					while (nbrOfSets + dataSetIndex) > 0:
						if enableDebugDump == 1:
							parseDataStr = " " + str(nbrOfSets) + " + " + str(dataSetIndex) + " > 0\n"
							print(parseDataStr)
							debugJonsonDump = debugJonsonDump + parseDataStr
						try:
							parsed_modRank = parsed['payload']['statistics_closed']['90days'][dataSetIndex]['mod_rank']
						except:
							parseDataStr = "Error: Parsing error of [mod_rank] for " + itemStr + "!"
							print(parseDataStr)
							parsed_modRank = 0
							if enableDebugDump == 1:
								debugJonsonDump = debugJonsonDump + parseDataStr
							break
						if enableDebugDump == 1:
							parseDataStr = "  " + str(nbrOfSets + dataSetIndex) + "(" + str(dataSetIndex) + ")" + ": " + str(parsed['payload']['statistics_closed']['90days'][dataSetIndex]) + "\n"
							print(parseDataStr)
							debugJonsonDump = debugJonsonDump + parseDataStr
							parseDataStr = "  parsed_modRank=" + str(parsed_modRank) + "\n"
							print(parseDataStr)
							debugJonsonDump = debugJonsonDump + parseDataStr
						# If the last set is not mod_rank=0 select the set -2 from end to parse
						if parsed_modRank == 0:
							break
						else:
							dataSetIndex -= 1
					#END while (nbrOfSets + dataSetIndex) > 0:
					parsed_modRank = None
					#breakpoint()
				if enableDebugDump == 1:
					parseDataStr = "Used set at index " + str(nbrOfSets + dataSetIndex) + ": " + str(parsed['payload']['statistics_closed']['90days'][dataSetIndex]) + "\n"
					print(parseDataStr)
					debugJonsonDump = debugJonsonDump + parseDataStr
			# END else:
			#breakpoint()
			# parse min. price
			try:
				parsed_min = parsed['payload']['statistics_closed']['90days'][dataSetIndex]['min_price']
			except:
				parseDataStr = "Error: Parsing error of [min_price] for " + itemStr + "!"
				print(parseDataStr)
				parsed_min = 0
				if enableDebugDump == 1:
					debugJonsonDump = debugJonsonDump + (parseDataStr + "\n")
			# parse max. price
			try:
				parsed_max = parsed['payload']['statistics_closed']['90days'][dataSetIndex]['max_price']
			except:
				parseDataStr = "Error: Failed parsing of [max_price] for " + itemStr + "!"
				print(parseDataStr)
				parsed_max = 0
				if enableDebugDump == 1:
					debugJonsonDump = debugJonsonDump + (parseDataStr + "\n")
			# parse median price
			try:
				parsed_median = parsed['payload']['statistics_closed']['90days'][dataSetIndex]['median']
				parsed_median = round(parsed_median)
			except:
				parseDataStr = "Error: Failed parsing of [median] for " + itemStr + "!"
				print(parseDataStr)
				parsed_median = 0
				if enableDebugDump == 1:
					debugJonsonDump = debugJonsonDump + (parseDataStr + "\n")
			# parse sold volume
			try:
				parsed_volume = parsed['payload']['statistics_closed']['90days'][dataSetIndex]['volume']
			except:
				parseDataStr = "Error: Failed parsing of [volume] for " + itemStr + "!"
				print(parseDataStr)
				parsed_volume = 0
				if enableDebugDump == 1:
					debugJonsonDump = debugJonsonDump + (parseDataStr + "\n")
			# parse date
			try:
				date_time = parsed['payload']['statistics_closed']['90days'][dataSetIndex]['datetime']
			except:
				parseDataStr = "Error: Failed parsing of [datetime] for " + itemStr + "!"
				print(parseDataStr)
				date_time = "9999-99-99"
				if enableDebugDump == 1:
					debugJonsonDump = debugJonsonDump + (parseDataStr + "\n")
			parsed = None
		#Since there are exeption on warframe market, where for example the sevagoth prime set is just calles "sevagoth prime"
		# we manually add the set here to have it uniform wit hthe rest or the frame sets
		#breakpoint()
		if itemStr == 'Sevagoth Prime':
			itemStr = 'Sevagoth Prime Set'
		elif itemStr == 'Epitaph Prime':
			itemStr = 'Epitaph Prime Set'
		elif itemStr == 'Nautilus Prime':
			itemStr = 'Nautilus Prime Set'
		elif 'Zid-an-' in itemStr:
			itemStr = itemStr.replace('Zid-an-', 'Zid-an ')
			itemStr = string.capwords(itemStr)
		#Build the data 
		parseDataStr = "The price on " + date_time[:10] + " for a sold volume of " + str(parsed_volume) + " is " + str(parsed_min) + " to " + str(parsed_max) + " (median " + str(parsed_median) + ") platinum for " + itemStr
		print(parseDataStr)
		if enableDebugDump == 1:
			debugJonsonDump = debugJonsonDump + (parseDataStr + "\n")
		#breakpoint()
		# Add the new data line with the scraped data
		newDataLine = [date_time[:10], str(parsed_volume), str(parsed_min), str(parsed_max), str(parsed_median), itemStr]
		my_data.append(newDataLine)
		if enableDebugDump == 1:
			parseDataStr = "parsed_median=" + str(parsed_median) + " > maxMedian=" + str(maxMedian) + " ?\n"
			print(parseDataStr)
			debugJonsonDump = debugJonsonDump + parseDataStr
		if parsed_median > maxMedian:
			maxMedian = parsed_median
			maxMedianLineIndex = currentLineIndex
			if enableDebugDump == 1:
				parseDataStr = " Yes -> maxMedianLineIndex=" + str(maxMedianLineIndex) + "\n"
				print(parseDataStr)
				debugJonsonDump = debugJonsonDump + parseDataStr
		elif enableDebugDump == 1:
			parseDataStr = " No\n"
			print(parseDataStr)
			debugJonsonDump = debugJonsonDump + parseDataStr
		currentLineIndex += 1
		sleep(0.1) # wait 300 ms
	#END for item in my_itemList:
	my_itemList = None
	dataSetIndex = None
	itemStr = None
	item = None
	maxMedian = None
	currentLineIndex = None
	parsed_min = None
	parsed_max = None
	parsed_median = None
	parsed_volume = None
	date_time = None
	try:
		parseDataStr = "\nThe most valuable item currently is " + my_data[maxMedianLineIndex][5] + " with a median of " + my_data[maxMedianLineIndex][4] + " platinum.\n"
		maxMedianLineIndex = None
		print(parseDataStr)
		if enableDebugDump == 1:
			debugJonsonDump = debugJonsonDump + parseDataStr
	except:
		parseDataStr = "Error: Failed to scrape anything!\n"
		print(parseDataStr)
		if enableDebugDump == 1:
			debugJonsonDump = debugJonsonDump + parseDataStr
	else:
		if enableDebugDump == 1:
			parseDataStr = "my_data=" + str(my_data) + "\n"
			print(parseDataStr)
			debugJonsonDump = debugJonsonDump + parseDataStr
	# End else:
	#breakpoint()
	script_dir = str(Path( __file__ ).parent.absolute()) + "/"
	# Store the received data in a txt-file (only for debug)
	if enableDebugDump > 0:
		fileName = script_dir + fileNameAddon + listName + "_DebugDump.txt"
		parseDataStr = "\nStore debug dump into [" + fileName + "]."
		print(parseDataStr)
		debugJonsonDump = debugJonsonDump + parseDataStr
		with open(fileName, 'w') as debugDumpFile:
			debugDumpFile.write(debugJonsonDump)
	# Store the extracted data in a csv-file
	#breakpoint()
	now = datetime.now() # current date and time
	parseDataStr = now.strftime("%Y-%m-%d")
	fileName = script_dir + fileNameAddon + listName + "_" + parseDataStr +".csv"
	now = None
	# In manual mode ask the user if he wants to save the data
	if mode == "manually":
		print("Save the results to " + fileName + "? y/n")
		answer = input()
	else:
		print("Save the results to " + fileName + ".\n")
		answer = "y"
	
	if answer == "y":
		with open(fileName, 'w', newline='') as outputFile:
			wr = csv.writer(outputFile, dialect='excel')
			try:
				wr.writerows(my_data)
			except:
				print("Error: Failed to create the CSV-file!")
			else:
				print("Successfully created the CSV-file.")
	script_dir = None
	my_data = None
	parseDataStr = None
	fileNameAddon = None
	if enableDebugDump > 0:
		debugJonsonDump = None
	if mode == "manually":
		print("Goodbye...")
		answer = input() # A quick and dirty "Press anny key to quit"
	mode = None


# Request to open search on warframe.market (not used)
#	def browser_open():
#		print('Would you like to buy/sell ' + string.capwords(search) + "? y/n")
#		browser_answer = input()
#		if browser_answer == "y":
#			webbrowser.open_new('https://warframe.market/items/' + search.replace(' ', '_'))
#		#if browser_answer == "n":
#	browser_open()

# Start the script (used to build everything or select a list)
def start_script():
	# Check and setup the items database
	global warframe_market_database
	if warframe_market_database is None:
		print("No item database found. Creating it now...")
		if ItemFinder.update_database():
			import warframe_market_database
			print("Item database created successfully.\n")
		else:
			print("Failed to create item database.")
			input("Press Enter to exit...")
			return
	else:
		print("Do you want to update the Warframe Market item database first? y/n")
		update_answer = input()
		if update_answer.lower() == "y":
			# Use ItemFinder.py to extract the current selleable items database from Warframe.Market
			print("Updating item database...")
		
			try:
				if ItemFinder.update_database():
					importlib.reload(warframe_market_database)
					print("Item database updated successfully.\n")
			except Exception as e:
				print("Error updating database:")
				print(e)
				input("Press Enter to continue using the old database...")
    # Let the user select the Item categories to scrape
	print('You can either scrape everything or select a specific item list.\nDo you want to scrape the whole warframe.market (takes some time)? y/n')
	answer = input()
	if answer == "y":
	# --------------------------------------- [START: Set this according to your needs] ---------------------------------------------
		warframeMarketScraper("1")
		warframeMarketScraper("2")
		warframeMarketScraper("3")
		warframeMarketScraper("4")
		warframeMarketScraper("5")
		warframeMarketScraper("6")
		warframeMarketScraper("7")
		warframeMarketScraper("8")
		warframeMarketScraper("9")
	# --------------------------------------- [END: Set this according to your needs] ---------------------------------------------
		print("Goodbye...")
		answer = input() # A quick and dirty "Press anny key to quit"
	elif answer == "n":
		warframeMarketScraper("manually")
	else:
		print("Goodbye...")
		answer = input() # A quick and dirty "Press anny key to quit"

start_script()

